[package]
name = "pbs-community/pbs-rewrite"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
private = true

[dependencies]
PakNet = "isoopod/paknet@^0.4.2"
Pack = "isoopod/pack@^0.7"